language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: gcs
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
